#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Emmaus.Resource", IsApplication=false)]

namespace Emmaus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int rvp_flingFactor = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int rvp_inertia = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int rvp_millisecondsPerInch = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int rvp_singlePageFling = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int rvp_triggerOffset = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030002
			public static int rvp_fragment_container = 2130903042;
			
			// aapt resource value: 0x7f030000
			public static int transition_current_scene = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int transition_scene_layoutid_cache = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int rvp_fragment_container = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerViewPager = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int RecyclerViewPager_rvp_flingFactor = 1;
			
			// aapt resource value: 3
			public static int RecyclerViewPager_rvp_inertia = 3;
			
			// aapt resource value: 4
			public static int RecyclerViewPager_rvp_millisecondsPerInch = 4;
			
			// aapt resource value: 2
			public static int RecyclerViewPager_rvp_singlePageFling = 2;
			
			// aapt resource value: 0
			public static int RecyclerViewPager_rvp_triggerOffset = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
